### ISSUE TITLE
Log file of loss values

### ISSUE THREAD

**Issue by hdjsjyl** [Jia-Research-Lab/ReviewKD#9]
Hi Author, thanks for your excellent work. I want to ask whether you can release a log file that includes loss values. Based on this file, I can check what‘s the loss change? It is better for the detection model. It would be the best for retinanet. Thank you!

**Comment by akuxcw** [comment]
Please provide your email, thanks.

**Comment by hdjsjyl** [comment]
> Please provide your email, thanks.

Hi Author, my email is hdjsjyl@gmail.com. Thank you so much!
